spring:
  application:
    name: telemetry-service
  profiles:
    active: dev #development mode
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

telemetry:
  voltage:
    min: 198.0
    max: 242.0
  frequency:
    min: 49.0
    max: 51.0
  thresholds:
    default-max-temperature: 80.0
    default-max-vibration: 10.0
  analytics:
    window-hours: 24