spring:
  application:
    name: telemetry-service
  profiles:
    active: dev #development mode

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

telemetry:
  thresholds:
    voltage:
      min: 207.0
      max: 253.0
    frequency:
      min: 49.0
      max: 51.0