-- Initial schema for the telemetry hub.
-- Matches the JPA entities (Telemetry, SensorThresholds); Hibernate runs with ddl-auto=validate.

CREATE TABLE telemetry_data (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id   VARCHAR(255),
    location    VARCHAR(255),
    voltage     DOUBLE PRECISION,
    current     DOUBLE PRECISION,
    frequency   DOUBLE PRECISION,
    temperature DOUBLE PRECISION,
    vibration   DOUBLE PRECISION,
    status      VARCHAR(255),
    timestamp   TIMESTAMP(6)
);

CREATE TABLE sensor_configs (
    sensor_id       VARCHAR(255) PRIMARY KEY,
    max_temperature DOUBLE PRECISION,
    max_vibration   DOUBLE PRECISION
);

-- The analytics aggregation filters by sensor_id and a time window
CREATE INDEX idx_telemetry_sensor_id_timestamp ON telemetry_data (sensor_id, timestamp);
